#!/bin/sh

# This file is sourced from roles where the UAA URL is relevant
export HCP_IDENTITY_EXTERNAL_PORT=${HCP_IDENTITY_EXTERNAL_PORT:-2793}
export HCF_UAA_INTERNAL_HOSTNAME=${KUBERNETES_NAMESPACE}.uaa.${DOMAIN}
export HCP_IDENTITY_INTERNAL_PORT=${HCP_IDENTITY_EXTERNAL_PORT}
export HCF_UAA_EXTERNAL_URL="https://${KUBERNETES_NAMESPACE}.uaa.${DOMAIN}:${HCP_IDENTITY_EXTERNAL_PORT}"
export HCF_UAA_INTERNAL_URL=$HCF_UAA_EXTERNAL_URL
