# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Requires a Windows 2012 R2 vagrant box built with https://github.com/joefitzgerald/packer-windows
  config.vm.box = "windows_2012_r2"

  config.vm.network "private_network", ip: "192.168.77.78"

  config.vm.provider "virtualbox" do |vb, override|
     # Core alternative:
     # override.vm.box = "https://hcfwin.azureedge.net/windows_2012_r2_core_virtualbox.box"
     override.vm.box = "https://hcfwin.azureedge.net/windows_2012_r2_virtualbox.box"
     vb.memory = "2048"
     # vb.gui = true
     override.vm.synced_folder "../", "/hcf"
  end

  config.vm.provision "file", source: "container-host-files/diego-kit/install-diego.ps1", destination: "C:\\diego-kit\\intall-diego.ps1"

  config.vm.provision "shell", inline: <<-SHELL
    & C:\\diego-kit\\intall-diego.ps1
    echo "Diego Windows installation finished."
  SHELL
end
