# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.network "private_network", ip: "192.168.77.78"

  config.vm.synced_folder "../", "/hcf"

  config.vm.provider "virtualbox" do |vb, override|
     override.vm.box = "https://hcfwin.azureedge.net/windows_2012_r2_sysprepvm_gvlk_virtualbox_v2.box"
     vb.memory = "2048"
     # vb.gui = true
  end

  config.vm.provider "vmware_fusion" do |vb, override|
    override.vm.box = "https://hcfwin.azureedge.net/windows_2012_r2_sysprepvm_gvlk_vmware_v2.box"
    vb.memory = "2048"
    # vb.gui = true
  end

  config.vm.provider "vmware_workstation" do |vb, override|
    override.vm.box = "https://hcfwin.azureedge.net/windows_2012_r2_sysprepvm_gvlk_vmware_v2.box"
    vb.memory = "2048"
    # vb.gui = true
  end

  config.vm.provision "file", source: "container-host-files/diego-kit/install-garden.ps1", destination: "C:\\diego-kit\\install-garden.ps1"
  config.vm.provision "file", source: "container-host-files/diego-kit/install-diego.ps1", destination: "C:\\diego-kit\\install-diego.ps1"
  config.vm.provision "file", source: "container-host-files/diego-kit/set-proxy.ps1", destination: "C:\\diego-kit\\set-proxy.ps1"

  config.vm.provision "shell", inline: <<-SHELL
    & C:\\diego-kit\\install-garden.ps1
    & C:\\diego-kit\\install-diego.ps1
    & C:\\diego-kit\\set-proxy.ps1
    echo "Diego Windows installation finished."
  SHELL
end
