#!/usr/bin/env bash
set -o errexit -o nounset

workdir="${1}"			; shift
CF_NAMESPACE="${1}"		; shift
engine="${1}"			; shift
enginev="${1}"			; shift
chartv="${1}"			; shift
chartlocation="${1}"		; shift
CLUSTER_ADMIN_PASSWORD="${1}"	; shift

# General operation - Testing a single chart for a specific engine.
# a. Make a copy of the node-env application in the brain test resources.
# b. Place the chart index into the app, as `index.yaml`.
# c. For all but postgres further:
#    1. Pull the stable chart archive from the indicated location
#    2. Unpack, patch and repack the archive
#    3. Place the modified archive into the app
#    4. Edit the index.yaml to refer to new location of the archive.
# d. Target the cluster, and push the node-env application
# e. Run the brain test customized to run only a single test case,
#    specific to the minibroker engine, and configured to use the
#    node-env app as its helm chart repository.
# f. Capture test result
# g. Delete node-env application serving as helm repository

# Location .............................................................

: "${GIT_ROOT:=$(git rev-parse --show-toplevel)}"
cd "${GIT_ROOT}"

# Configuration ........................................................

bin="${GIT_ROOT}/tooling/mb-chart-assessment"
stem=kube-chart-index
master="${workdir}/charts-master-index.yaml"

stable=https://kubernetes-charts.storage.googleapis.com
index="${stable}/index.yaml"

# Setup ................................................................

source "${GIT_ROOT}/make/include/colors"

LOG="${workdir}/${engine}/${enginev}-${chartv}.log"

sep() {
    >> "${LOG}" echo -e "\n....................................... $1\n"
}

rm -f "${LOG}"
touch "${LOG}"

echo -n '  -' $(blue "${engine}") $(blue "${enginev}"), chart $(blue "${chartv}") ...

# When engines are added we may have to adapt this to any other
# special cases, i.e. divergences between engine name and test case
# name.
case $engine in
    postgresql) testcase="_minibroker_postgres"	 ;;
    *)          testcase="_minibroker_${engine}" ;; 
esac

# ______________________________________________________________________
# 3.d, 3.e
#
sep 'helm repo setup ...'
echo -n ' helm repo starting ...'
HREPOS="$("${bin}/local-chart-repository" start \
		"${LOG}" "${GIT_ROOT}" "${workdir}" "${CF_NAMESPACE}" \
		"${workdir}/${engine}/${enginev}-${chartv}.yaml" \
		"${engine}" "${chartlocation}" "${CLUSTER_ADMIN_PASSWORD}" || true)"

if [ "${HREPOS}" == "" ]
then
    echo "$(left 12)$(eeol)$(red "start failed"), likely a patch failure"
    echo FAIL "${engine}" "${enginev}" "${chartv}" >> "${workdir}/chart-results.csv"
    exit 1
fi

echo -n "$(left 12)$(eeol)$(green up),"

# ______________________________________________________________________
# 3.f, 3.g
# We force the test to use the custom helm repository we prepared and
# started in 3.d, 3.e.
sep 'testing ...'
echo -n ' testing ...'
if make/tests acceptance-tests-brain \
	      "env.INCLUDE=${testcase}" \
	      "env.KUBERNETES_REPO=${HREPOS}" \
	      "env.VERBOSE=true" \
	      >> "${LOG}" 2>&1
then
    echo -n "$(left 3)$(eeol)$(green OK)"
    echo _OK_ "${engine}" "${enginev}" "${chartv}" >> "${workdir}/chart-results.csv"
else
    echo -n "$(left 3)$(eeol)$(red FAIL)"
    echo FAIL "${engine}" "${enginev}" "${chartv}" >> "${workdir}/chart-results.csv"
fi

# ______________________________________________________________________
sep 'post assessment service & broker state ...'
(
    cf marketplace || true
    cf service-brokers || true

    # A failed chart can leave orphans behind (failed to delete service instance, failed to delete broker).
    # Without fixing this all future trials will also fail, using the wrong broker.
    # We purge the service itself first, after that we can cleanup the broker as well.

    if cf service-brokers | grep minibroker
    then
	cf purge-service-offering -f "${engine}" || true
	cf delete-service-broker -f "$(cf service-brokers | grep minibroker | awk '{print $1}')" || true
    fi
) >> "${LOG}" 2>&1

# ______________________________________________________________________
#
sep 'helm repo teardown ...'
echo -n ' helm repo stopping ...'
(
    "${bin}/local-chart-repository" stop
) >> "${LOG}" 2>&1
echo -n "$(left 12)$(eeol)$(blue down),"

echo ' done'
