.tags: &tags
- personal-minikube-tassis

stages:
- lint
- build
- publish

lint:
  stage: lint
  tags: *tags
  image: thulioassis/bazel-docker-image:0.29.1
  script:
  - ./dev/linters/shellcheck.sh

build:chart:
  stage: build
  tags: *tags
  image: thulioassis/bazel-docker-image:0.29.1
  script:
  - bazel build //deploy/helm/scf:chart
  - mkdir -p output; (cd bazel-bin/deploy/helm/scf; tar cf - .) | (cd output; tar xvf -)
  artifacts:
    paths:
    - output/scf-*.tgz
    expire_in: 1 week

publish:chart:
  stage: publish
  tags: *tags
  image: minio/mc
  script:
  - mc config host add "s3" "https://s3.amazonaws.com" "${AWS_ACCESS_KEY}" "${AWS_SECRET_KEY}"
  - mc cp output/scf-*.tgz "s3/scf-v3"
  - >-
    echo "URL: https://scf-v3.s3.amazonaws.com/$(find output/ -name 'scf-*.tgz' -print0 | xargs -0 basename)"
