kubectl create --namespace hcf -f test-kube/nats.yml
kubectl create --namespace hcf -f test-kube/consul.yml
kubectl create --namespace hcf -f test-kube/mysql.yml
kubectl create --namespace hcf -f test-kube/mysql-proxy.yml
kubectl create --namespace hcf -f test-kube/etcd.yml
kubectl create --namespace hcf -f test-kube/diego-database.yml
kubectl create --namespace hcf -f test-kube/router.yml
kubectl create --namespace hcf -f test-kube/tcp-router.yml
kubectl create --namespace hcf -f test-kube/routing-api.yml
kubectl create --namespace hcf -f test-kube/uaa.yml
kubectl create --namespace hcf -f test-kube/api.yml
kubectl create --namespace hcf -f test-kube/api-worker.yml
kubectl create --namespace hcf -f test-kube/blobstore.yml
kubectl create --namespace hcf -f test-kube/clock-global.yml
kubectl create --namespace hcf -f test-kube/doppler.yml
kubectl create --namespace hcf -f test-kube/loggregator.yml
kubectl create --namespace hcf -f test-kube/diego-brain.yml
kubectl create --namespace hcf -f test-kube/diego-cc-bridge.yml
kubectl create --namespace hcf -f test-kube/diego-route-emitter.yml
kubectl create --namespace hcf -f test-kube/diego-access.yml
kubectl create --namespace hcf -f test-kube/diego-cell.yml
