# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.network "private_network", ip: "192.168.77.79"

  config.vm.synced_folder "../../../", "/hcf"

  config.vm.provider "virtualbox" do |vb, override|
     override.vm.box = "https://hcfwin.azureedge.net/windows_2012_r2_sysprepvm_gvlk_virtualbox_v2.box"
     vb.memory = "2048"
     # vb.gui = true
  end

  config.vm.provision "file", source: "setup-hcf-network.ps1", destination: "C:\\hcf-windows-scripts\\setup-hcf-network.ps1"
  config.vm.provision "file", source: "build-cnap-image.ps1", destination: "C:\\hcf-windows-scripts\\build-cnap-image.ps1"

  config.vm.provision "shell", inline: <<-SHELL
    & C:\\hcf-windows-scripts\\setup-hcf-network.ps1
    & C:\\hcf-windows-scripts\\build-cnap-image.ps1
    echo "Windows box ready. IP Address: '192.168.77.79'. Username: 'vagrant'. Password: 'vagrant'."
    echo "Execute run-cnap-image.rb to start windows-cell"
  SHELL
end
