#!/usr/bin/env bash

set -o errexit -o nounset

: "${GIT_ROOT:=$(git rev-parse --show-toplevel)}"
source "${GIT_ROOT}/make/include/has_namespace"
source "${GIT_ROOT}/make/include/has_release"
source "${GIT_ROOT}/make/include/defaults"

printf "Stopping and cleaning up %s release...\\n" "${NGINX_INGRESS_HELM_RELEASE}"

if has_release "${NGINX_INGRESS_HELM_RELEASE}"; then
  helm delete --purge "${NGINX_INGRESS_HELM_RELEASE}"
fi

if has_namespace "${NGINX_INGRESS_NAMESPACE}"; then
  kubectl delete namespace "${NGINX_INGRESS_NAMESPACE}"
fi
