#!/usr/bin/env bash

set -o nounset

if [ -z "${INGRESS_CONTROLLER:-}" ]; then
  exit
fi

: "${GIT_ROOT:=$(git rev-parse --show-toplevel)}"

if [ -x "${GIT_ROOT}/make/ingress/${INGRESS_CONTROLLER}/stop" ]; then
  exec "${GIT_ROOT}/make/ingress/${INGRESS_CONTROLLER}/stop"
fi
