---
{{- if .Values.enable.eirini }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.env.EIRINI_KUBE_NAMESPACE | quote}}
{{- if and (eq (printf "%s" .Values.kube.auth) "rbac") (.Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1") }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eirini
  namespace: {{.Values.env.EIRINI_KUBE_NAMESPACE | quote}}
rules:
- apiGroups: ['*']
  resources: ['*']
  verbs:     ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eirini
  namespace: {{.Values.env.EIRINI_KUBE_NAMESPACE | quote}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eirini
subjects:
- kind: ServiceAccount
  name: eirini
  namespace: {{.Release.Namespace}}
{{- end }}
{{- end }}
