---
{{- if .Values.enable.eirini }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: eirini-loggregator-fluentd
spec:
  selector:
    matchLabels:
      name: eirini-loggregator-fluentd
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: eirini-loggregator-fluentd
    spec:
      serviceAccountName: "eirini"
      initContainers:
      - name: copy-certs
        env:
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              {{- if .Values.secrets.INTERNAL_CA_CERT }}
              name: "secrets"
              {{- else }}
              name: "secrets-{{.Chart.Version}}-{{.Values.kube.secrets_generation_counter}}"
              {{- end }}
        - name: REGISTRY
          value: "registry.{{.Values.env.DOMAIN}}"
        - name: SCF_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{.Values.env.EIRINI_CERT_COPIER_IMAGE | quote}}
        volumeMounts:
        - name: host-docker
          mountPath: /workspace/docker
      containers:
      - name: eirini-loggregator-fluentd
        image: {{.Values.env.EIRINI_FLUENTD_IMAGE | quote}}
        imagePullPolicy: Always
        env:
        - name: FLUENT_UID
          value: "0"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: vardata
          mountPath: /var/data
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varvcapstore
          mountPath: /var/vcap/store
          readOnly: true
        - name: varvcapdata
          mountPath: /var/vcap/data
          readOnly: true
        - name: loggregator-tls-certs
          mountPath: /fluentd/certs
          readOnly: true
      - name: loggregator-agent
        # XXX untagged image from dockerhub!
        image: loggregator/agent
        imagePullPolicy: Always
        env:
        - name: AGENT_METRIC_SOURCE_ID
          value: scf/daemonset/loggregator-fluentd
        # Note: KUBERNETES_CLUSTER_DOMAIN hard-coded to "cluster.local"
        - name: ROUTER_ADDR
          value: "doppler-doppler.{{.Release.Namespace}}.svc.cluster.local:8082"
        - name: ROUTER_ADDR_WITH_AZ
          value: "doppler-doppler.{{.Release.Namespace}}.svc.cluster.local:8082"
        - name: AGENT_PPROF_PORT
          value: "6062"
        - name: AGENT_HEALTH_ENDPOINT_PORT
          value: "6063"
        ports:
        - name: health
          containerPort: 6063
        volumeMounts:
        - name: loggregator-tls-certs
          mountPath: /srv/certs
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vardata
        hostPath:
          path: /var/data
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varvcapstore
        hostPath:
          path: /var/vcap/store/
      - name: varvcapdata
        hostPath:
          path: /var/vcap/data/
      - name: loggregator-tls-certs
        secret:
          secretName: "secrets-{{.Chart.Version}}-{{.Values.kube.secrets_generation_counter}}"
          items:
            - key: loggregator-agent-cert
              path: agent.crt
            - key: loggregator-agent-cert-key
              path: agent.key
            - key: internal-ca-cert
              path: ca.crt
      - name: host-docker
        hostPath:
          path: /etc/docker
          type: Directory
{{- end }}
