{{- if .Values.enable.eirini }}
apiVersion: v1
kind: Service
metadata:
  name: opi-registry
  labels:
    {{- template "scf.role-labels" "opi-registry" }}
    {{- template "scf.labels" . }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app.kubernetes.io/component: bits
  type: NodePort
{{- end }}
