system_domain: ~
deployment_name: scf

releases:
  # The defaults for all releases, where we do not otherwise override them.
  defaults:
    url: docker.io/cfcontainerization
    stemcell:
      os: opensuse-42.3
      version: 36.g03b4653-30.80-7.0.0_340.g2b599a90

sizing:
  HA: false

# Service is only valid to set an external endpoint for the router if features.ingress.enabled is
# false.
service:
  type: LoadBalancer
  externalIPs: []
  clusterIP: ~

features:
  eirini: false
  ingress:
    enabled: false
    tls:
      crt: ~
      key: ~
    annotations: {}
  # TODO: suse_buildpacks should be default to true after the opensuse-stemcell-based images are
  # published to docker.io.
  suse_buildpacks: false

operations:
  # A list of configmap names that should be applied to the BOSH manifest.
  custom: []

k8s-host-url: ""
k8s-service-token: ""
k8s-service-username: ""
k8s-node-ca: ""

# Settings for using the upstream helm chart for NATS
# This needs to be here so that it can propagate into the subchart correctly.
nats:
  # Set this to true to disable the NATS release, and use the official helm chart
  # In that case the nats password is required.
  external: false
  auth:
    user:     nats # Erini hard codes this to "nats"
    password: pikachu
