system_domain: ~
deployment_name: scf

# Set or override job properties. The first level of the map is the instance group name. The second
# level of the map is the job name. E.g.:
#  properties:
#    adapter:
#      adapter:
#        scalablesyslog:
#          adapter:
#            logs:
#              addr: scf-log-api:8082
properties: {}

releases:
  # The defaults for all releases, where we do not otherwise override them.
  defaults:
    url: docker.io/cfcontainerization
    stemcell:
      os: opensuse-42.3
      version: 36.g03b4653-30.80-7.0.0_340.g2b599a90
  cf_acceptance_tests:
    properties:
      acceptance_tests:
        include: "" # e.g. "+docker,-ssh"

sizing:
  HA: false

# Service is only valid to set an external endpoint for the router if features.ingress.enabled is
# false.
service:
  type: LoadBalancer
  externalIPs: []
  clusterIP: ~

features:
  eirini: false
  ingress:
    enabled: false
    tls:
      crt: ~
      key: ~
    annotations: {}
  # TODO: suse_buildpacks should be default to true after the opensuse-stemcell-based images are
  # published to docker.io.
  suse_buildpacks: false

operations:
  # A list of configmap names that should be applied to the BOSH manifest.
  custom: []

k8s-host-url: ""
k8s-service-token: ""
k8s-service-username: ""
k8s-node-ca: ""
