#!/bin/sh

# This file can be called numerous times from the various flows through `make *`, but
# only set the FISSILE-* env vars if they're unset, 
# or this file is sourced from an interactive shell.

if [ -z "${FISSILE_RELEASE:-}" ] || ( [ $0 = "-bash" ] && [ -n "${BASH_SOURCE:-}" ] && [ ${#BASH_SOURCE[@]} -eq 1 ] ) ; then
    if [ -z "${GIT_ROOT:-}" ] ; then
	GIT_ROOT=$(dirname $(dirname $(cd $(dirname "${BASH_SOURCE[0]}") && echo ${PWD})))
    fi
    . ${GIT_ROOT}/bin/.fissilerc
fi
