#!/usr/bin/env bash
# Access to secrets

get_secret () {
  nargs=$#
  if (( nargs != 3 )); then
    (>&2 printf "Wrong number of arguments.\n")
    (>&2 printf "Usage: get_secret <namespace> <container_name> <env_name>\n")
    return 1
  fi

  local namespace="$1"
  local container_name="$2"
  local env_name="$3"

  secret_name="$(kubectl get pods \
    --namespace "${namespace}" \
    -o jsonpath='{.items[*].spec.containers[?(.name=="'${container_name}'")].env[?(.name=="'${env_name}'")].valueFrom.secretKeyRef.name}' | awk '{ print $1 }')"

  if [ -z "${secret_name}" ]; then
    (>&2 printf "Could not get secret name\n")
    return 1
  fi

  secret_key="$(kubectl get pods \
    --namespace "${namespace}" \
    -o jsonpath='{.items[*].spec.containers[?(.name=="'${container_name}'")].env[?(.name=="'${env_name}'")].valueFrom.secretKeyRef.key}' | awk '{ print $1 }')"

  if [ -z "${secret_key}" ]; then
    (>&2 printf "Could not get secret key\n")
    return 1
  fi

  kubectl get secret "${secret_name}" \
    --namespace "${namespace}" \
    -o jsonpath="{.data['${secret_key}']}" | base64 --decode
}
