#!/usr/bin/env bash
# Access to secrets

get_secret () {
    local ns="$1"
    local pod="$2"
    local ev="$3"

    name="$(kubectl get pods \
	--namespace "${ns}" \
	-o jsonpath='{.items[*].spec.containers[?(.name=="'${pod}'")].env[?(.name=="'${ev}'")].valueFrom.secretKeyRef.name}' | awk '{ print $1 }')"

    key="$(kubectl get pods \
	--namespace "${ns}" \
	-o jsonpath='{.items[*].spec.containers[?(.name=="'${pod}'")].env[?(.name=="'${ev}'")].valueFrom.secretKeyRef.key}' | awk '{ print $1 }')"

    kubectl get secret "${name}" \
	--namespace "${ns}" \
	-o jsonpath="{.data['${key}']}" | base64 -d -
}
