#!/bin/sh

set +o errexit +o nounset

test -n "${XTRACE}" && set -o xtrace

set -o errexit -o nounset

CF_VERSION=$(cat src/cf-release/releases/index.yml | y2j | jq '.builds[].version' | sed -e 's/"//g' | sort -nr | head -1)

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}
GIT_DESCRIBE=${GIT_DESCRIBE:-$(git describe --tags --long)}
GIT_BRANCH=${GIT_BRANCH:-$(git name-rev --name-only HEAD | sed -e 's/[^-a-zA-Z0-9_.]/_/g')}

GIT_SUBTAG=${GIT_SUBTAG:-pre}
GIT_TAG=${GIT_TAG:-$(echo ${GIT_DESCRIBE} | awk -F - '{ print $1 }' )}
GIT_COMMITS=${GIT_COMMITS:-$(echo ${GIT_DESCRIBE} | awk -F - '{ print $2 }' )}
GIT_SHA=${GIT_SHA:-$(echo ${GIT_DESCRIBE} | awk -F - '{ print $3 }' )}

ARTIFACT_NAME=${ARTIFACT_NAME:-$(basename $(git config --get remote.origin.url) .git | sed s/^hcf-//)}
APP_VERSION=${GIT_TAG}-${GIT_SUBTAG}+cf${CF_VERSION}.${GIT_COMMITS}.${GIT_SHA}
DOCKER_APP_VERSION=$(echo ${APP_VERSION} | tr + -)
