#!/usr/bin/env bash

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. "${GIT_ROOT}/.envrc"
. "${GIT_ROOT}/make/include/versioning"

fissile build images --add-label "version.cap=$DOCKER_APP_VERSION"
