#!/bin/bash

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. "${GIT_ROOT}/.envrc"

BOSH_IMAGES=${BOSH_IMAGES:-$(fissile show image)}

for image in ${BOSH_IMAGES}; do
    # Redirect docker stdout to avoid polluting logfiles with progressbar characters
    echo Pushing "${image}" ...
    docker push "${image}" > /dev/null
done
