#!/usr/bin/env bash

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}
NAMESPACE="cf"

has_namespace() {
    kubectl get namespace --output=name "${NAMESPACE}" >/dev/null 2>/dev/null
}

stampy "${GIT_ROOT}/scf_metrics.csv" "$0" make-brain start

if has_namespace ; then
    :
else
    echo 1>&2 Namespace "${NAMESPACE}" is missing. SCF is not running.
    exit 1
fi

stampy "${GIT_ROOT}/scf_metrics.csv" "$0" make-brain::setup start

source "${GIT_ROOT}/bin/settings/settings.env"
source "${GIT_ROOT}/bin/settings/network.env"

cf api api."${DOMAIN}" --skip-ssl-validation
cf auth admin "${CLUSTER_ADMIN_PASSWORD}"
cf enable-feature-flag diego_docker

stampy "${GIT_ROOT}/scf_metrics.csv" "$0" make-brain::setup end

stampy "${GIT_ROOT}/scf_metrics.csv" "$0" make-brain::create start

# Delete left-over pod/definition from previous runs, then create/run
kubectl delete --namespace="${NAMESPACE}" --filename="kube/bosh-task/acceptance-tests-brain.yml" \
    2> /dev/null || /bin/true

printf "Waiting for namespace %s to be deleted...\n" "${NAMESPACE}"
while has_namespace ; do
    sleep 1
done

kubectl create --namespace="${NAMESPACE}" --filename="kube/bosh-task/acceptance-tests-brain.yml"

stampy "${GIT_ROOT}/scf_metrics.csv" "$0" make-brain::create end

i=0

while [ "$(k get pod "${NAMESPACE}":acceptance-tests-brain -o=json | jq -r .status.phase)" != "Running" ]
do
  i=$((i + 1))
  if [ ${i} -gt 30 ]
  then
    echo "acceptance-tests-brain container failed to reach Running state"
    exit 1
  fi
  sleep 1
done

stampy "${GIT_ROOT}/scf_metrics.csv" "$0" make-brain::log end

# First show the logs accumulated so far, then stream further logs in
# a way which terminates when the pod (= testsuite) terminates.
k logs   "${NAMESPACE}":acceptance-tests-brain
k attach "${NAMESPACE}":acceptance-tests-brain

stampy "${GIT_ROOT}/scf_metrics.csv" "$0" make-brain::log end
stampy "${GIT_ROOT}/scf_metrics.csv" "$0" make-brain 'done'
