#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}
certgen_root=${certgen_docker_root:-$(mktemp -d)}
function finish {
  rm -rf "${certgen_root}"
}

trap finish EXIT

for OS in ${OSES:-linux darwin} ; do
  mkdir -p "${certgen_root}/${OS}/scripts"
  sed "s#@@CERTSTRAP_OS@@#${OS}#" \
    "${GIT_ROOT}/bin/cert-generator-wrapper.sh.in" \
    > "${certgen_root}/${OS}/cert-generator.sh"
  chmod a+x "${certgen_root}/${OS}/cert-generator.sh"
  cp "${GIT_ROOT}/bin/generate-dev-certs.sh" "${certgen_root}/${OS}/scripts/generate-scf-certs.sh"
  cp "${GIT_ROOT}/src/uaa-fissile-release/generate-certs.sh" "${certgen_root}/${OS}/scripts/generate-uaa-certs.sh"
  url="https://cf-opensusefs2.s3.amazonaws.com/certstrap/certstrap-${CERTSTRAP_VERSION}.${OS}-amd64.tgz"
  printf "Downloading from %s...\n" "${url}"
  curl "${url}" | tar -xzC "${certgen_root}/${OS}/scripts/" certstrap

  tar czf output/scf-cert-generator.${OS}-amd64.tgz -C "${certgen_root}/${OS}" cert-generator.sh scripts/
done
