#!/bin/sh

set -o errexit -o nounset

MAKEDIR=$(cd $(dirname $0) ; pwd)

. ${MAKEDIR}/include/registry

docker ps --all --format '{{.ID}} {{.Image}}' |
  perl -ne 'my @a = split; print "$a[0]\n" if $a[1] =~ m{\A(?:(?:$ENV{IMAGE_REGISTRY}/)?$ENV{IMAGE_ORG}|dev-service-[-_\w]+:)}' |
  xargs --no-run-if-empty docker rm --force
