#!/bin/sh

set -o errexit -o nounset

GIT_ROOT="${GIT_ROOT:-$(git rev-parse --show-toplevel)}"

. "${GIT_ROOT}/make/include/fissile"

FISSILE_VERSION=$(fissile version | sed 's/+/-/g')
IMAGE_NAME="fissile-cbase:${FISSILE_VERSION}"

if test -n "$(docker images --format '{{.}}' "${IMAGE_NAME}")" ; then
    exit 0 # We already have the image, don't do anything
fi

if docker pull "fissile/${IMAGE_NAME}" ; then
    docker tag "fissile/${IMAGE_NAME}" "${IMAGE_NAME}"
else
    FISSILE_FROM="${UBUNTU_IMAGE:-hpe-license-on-ubuntu:14.04}"
    export FISSILE_FROM
    fissile build layer compilation
fi
