#!/bin/sh

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

if [ "$1" = "--profile" ] ; then
  AUTOSCALER_PROFILE=$2
  shift 2
else
  AUTOSCALER_PROFILE=sample
fi

DOCKER_RUNTIME=${DOCKER_RUNTIME:-'maven:3-jdk-7'}

cd $GIT_ROOT/src/open-Autoscaler
for x in api server servicebroker ; do
  printf "Building %s...\n" $x
  docker run --rm \
     --volume ${GIT_ROOT}:${GIT_ROOT} \
     --workdir ${GIT_ROOT}/src/open-Autoscaler/$x \
     --entrypoint bash \
     ${DOCKER_RUNTIME} -l -c "rm -rf ./$x/target/ && mvn clean package -P${AUTOSCALER_PROFILE} -DskipTests"
done

release_path=${1:-${BOSH_RELEASE_PATH}}
release_name=${2:-${BOSH_RELEASE_NAME:-$(basename ${release_path} -release)}}

if [ -z $release_path -o -z $release_name ] ; then
  cat <<HELP
  Usage: generate-autoscaler-blobs [--profile PROFILE_NAME=sample] <RELEASE_PATH> <RELEASE_NAME>"
  \release_path must be relative to the root of hcf
  \$release_path=$release_path
  \$release_name=$release_name
HELP
  exit 1
fi

docker run \
    --interactive \
    --rm \
    --volume ${HOME}/.bosh:/root/.bosh \
    --volume $GIT_ROOT/:$GIT_ROOT/ \
    helioncf/hcf-pipeline-ruby-bosh \
    bash -l -c "rbenv global 2.2.3 && cd $GIT_ROOT/src/open-Autoscaler/bosh-release && rm -rf ../bosh-release/downloads/ && rm -rf ../bosh-release/blobs/* && scripts/generate_blobs.sh"
