#!/bin/sh

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. ${GIT_ROOT}/make/include/registry
. ${GIT_ROOT}/make/include/versioning

${GIT_ROOT}/bin/validation.sh

# If you're looking at these quotes and wondering what I was thinking...
# The quotes need to be escaped so echo doesn't consume them, because they need
# to be used in the `docker run` command further on, which already has quotes
# inside quotes... shell really needs a %Q operator or something.

OPTIONS=$(echo \
    --dtr \"${IMAGE_REGISTRY}\" \
    --dtr-org \"${IMAGE_ORG}\" \
    --hcf-prefix \"${IMAGE_PREFIX}\" \
    --hcf-tag \"${DOCKER_APP_VERSION}\" \
    --hcf-version \"${APP_VERSION}\" \
    --hcf-root-dir \"${GIT_ROOT}\"
)

CLEAN=""
TARGET=${1}

# Blacklist env directories and docker repositories that aren't meant for the target
case ${TARGET} in
  hcp|hcp-instance*)
    if [ `echo ${IMAGE_REGISTRY} | grep '\(potato\.helion\.lol\|docker\.helion\.lol\)'` ]; then
      printf "\033[0;1;31mPolitely refusing to use credential protected ${IMAGE_REGISTRY} for hcp (did you mean docker-registry.helion.space?)\033[0m\n" >&2
      exit 1
    fi
    ;;
esac

mkdir -p output

case ${TARGET} in
    vagrant)
        OUTFILE=${OUTFILE:-"${TARGET}.json"}
        OPTIONS="${OPTIONS} --provider \"${TARGET}\""

	fissile show properties --output yaml > vagrant-propmap.yaml

        OPTIONS="${OPTIONS} --property-map vagrant-propmap.yaml"
	CLEAN="${CLEAN} vagrant-propmap.yaml"
        ;;
    hcp)
        OUTFILE=${OUTFILE:-"output/sdl.json"}
        OPTIONS="${OPTIONS} --provider \"${TARGET}\""
        OPTIONS="${OPTIONS} --hcp-cpu-num 6"

	fissile show properties --output yaml > hcf-hcp-propmap.yaml

        OPTIONS="${OPTIONS} --property-map hcf-hcp-propmap.yaml"
	CLEAN="${CLEAN} hcf-hcp-propmap.yaml"
        ;;
    instance-basic-dev|instance-ha-dev)
        OUTFILE=${OUTFILE:-"output/${TARGET}.json"}
        TEMPLATE="hcp/${TARGET}.template.json"
        OPTIONS="${OPTIONS} --provider hcp-instance --instance-definition-template ${TEMPLATE}"
        ;;
    *)
        OUTFILE=${OUTFILE:-"hcf-${TARGET}.tf.json"}
        OPTIONS="${OPTIONS} --provider tf:$(echo ${TARGET} | sed -e 's@-spot@@' | tr - :)"
        ;;
esac

# Assemble AWS/MPC terraform from pieces, with variants overriding base definitions.
case ${TARGET} in
    mpc)
	cp terraform/mpc.tf ${GIT_ROOT}/
	;;
    aws*)
	cp terraform/aws/common/*.tf ${GIT_ROOT}/
	;;
esac
case ${TARGET} in
    aws-spot)
	cp terraform/aws/spot/*.tf ${GIT_ROOT}/
	;;
    aws-proxy)
	cp terraform/aws/proxy/*.tf ${GIT_ROOT}/
	;;
    aws-spot-proxy)
	cp terraform/aws/spot/*.tf       ${GIT_ROOT}/
	cp terraform/aws/proxy/*.tf      ${GIT_ROOT}/
	cp terraform/aws/spot-proxy/*.tf ${GIT_ROOT}/
	;;
esac

DOCKER_RUNTIME=${DOCKER_RUNTIME:-'helioncf/hcf-pipeline-ruby-bosh'}
ROLE_MANIFEST=${ROLE_MANIFEST:-'container-host-files/etc/hcf/config/role-manifest.yml'}

docker run \
       --rm \
       --volume ${GIT_ROOT}:${GIT_ROOT} \
       --workdir ${GIT_ROOT} \
       --entrypoint bash \
       ${DOCKER_RUNTIME} -l -c "RBENV_VERSION=2.2.3 bin/rm-transformer.rb ${OPTIONS} ${ROLE_MANIFEST}" \
    > ${OUTFILE}

rm -f $CLEAN

printf "%bGenerated %s%b\n" "\033[0;32m" "${OUTFILE}" "\033[0m"
