#!/bin/sh

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. ${GIT_ROOT}/make/include/registry
. ${GIT_ROOT}/make/include/versioning

# If you're looking at these quotes and wondering what I was thinking...
# The quotes need to be escaped so echo doesn't consume them, because they need
# to be used in the `docker run` command further on, which already has quotes
# inside quotes... shell really needs a %Q operator or something.

OPTIONS=$(echo \
              --dtr \"${IMAGE_REGISTRY}\" \
              --dtr-org \"${IMAGE_ORG}\" \
              --hcf-prefix \"${IMAGE_PREFIX}\" \
              --hcf-version \"${GIT_BRANCH}\"
)

if test -n ${ENV_DIR:-''}; then
    OPTIONS="${OPTIONS} --env \"${ENV_DIR}\""
fi

TARGET=${1}

case ${TARGET} in
    ucp)
        OUTFILE=${OUTFILE:-"hcf-${TARGET}.json"}
        OPTIONS="${OPTIONS} --provider \"${TARGET}\""
        ;;
    *)
        OUTFILE=${OUTFILE:-"hcf-${TARGET}.tf.json"}
        OPTIONS="${OPTIONS} --provider tf:$(echo ${TARGET} | tr - :)"

        cp terraform/${TARGET}.tf ${GIT_ROOT}/
        ;;
esac

DOCKER_RUNTIME=${DOCKER_RUNTIME:-'helioncf/hcf-pipeline-ruby-bosh'}
ROLE_MANIFEST=${ROLE_MANIFEST:-'container-host-files/etc/hcf/config/role-manifest.yml'}

docker run \
       --rm \
       --volume ${GIT_ROOT}:${GIT_ROOT} \
       --workdir ${GIT_ROOT} \
       --entrypoint bash \
       ${DOCKER_RUNTIME} -l -c "rbenv global 2.2.3 && bin/rm-transformer.rb ${OPTIONS} ${ROLE_MANIFEST} > ${OUTFILE}"

echo Generated ${OUTFILE}
