#!/bin/bash
set -o nounset

# This script is derived from part of
#	cf-ci:qa-pipelines/tasks/usb-deploy.sh

# # ## ### ##### ######## ############# #####################
## configuration

SUSE_REPO="https://kubernetes-charts.suse.com"
PATTERN="kubernetes-charts\\.suse\\.com"

# # ## ### ##### ######## ############# #####################

# Repository holding the charts for the sidecars

if [ $(helm repo list|grep -c "${PATTERN}") -gt 0 ] ; then
    printf "%bSUSE helm repository is installed already%b\n" "\033[0;32m" "\033[0m"
    exit 0
fi

printf "%bSUSE helm repository required, missing, starting installation ...%b\n" "\033[0;31;1m" "\033[0m"

helm repo add suse "${SUSE_REPO}"

# Check that the repo is now present
if [ $(helm repo list|grep -c "${PATTERN}") -lt 1 ] ; then
    printf "%bInstallation of SUSE helm repository failed%b\n" "\033[0;31;1m" "\033[0m"
    exit 1
fi

helm repo update
printf "%bUSE helm repository is now installed%b\n" "\033[0;32m" "\033[0m"
exit 0
