#!/bin/sh

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. ${GIT_ROOT}/make/include/fissile

UBUNTU_IMAGE=${UBUNTU_IMAGE:-'hpe-license-on-ubuntu:14.04'}

FISSILE_FROM=${UBUNTU_IMAGE} fissile build layer stemcell

