#!/bin/sh

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. ${GIT_ROOT}/make/include/fissile

FISSILE_VERSION=$(fissile version | sed 's/+/-/g')

docker pull fissile/fissile-role-base:${FISSILE_VERSION}
docker tag fissile/fissile-role-base:${FISSILE_VERSION} fissile-role-base:${FISSILE_VERSION}
