#!/bin/sh

set -o errexit
set -o verbose

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}
cd "${GIT_ROOT}"
source ${GIT_ROOT}/bin/common/versions.sh

# Download the Istio release.
curl -L https://raw.githubusercontent.com/istio/istio/master/release/downloadIstioCandidate.sh | ISTIO_VERSION=${ISTIO_VERSION} sh
export PATH=${GIT_ROOT}/istio-${ISTIO_VERSION}/bin:$PATH
istio_chart="${GIT_ROOT}/istio-${ISTIO_VERSION}/install/kubernetes/helm/istio"

# Make sure helm is ready.
if ! helm version | grep "Server:" > /dev/null 2>&1 ; then
  echo "helm is not ready"
  exit 1
fi

# Install Istio.
helm_args=(
    --name "istio"
    --namespace "istio-system"
    --values "bin/settings-istio.yaml"
)

helm install "${istio_chart}" "${helm_args[@]}" "$@"
