#!/bin/sh

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

cd "${GIT_ROOT}"

ENV_FILES="$(echo bin/settings/*.env bin/settings/kube/*.env)"

# TODO: We currently skip memory limits for development purposes

. "${GIT_ROOT}/make/include/registry"

fissile build kube \
    --kube-output-dir="${GIT_ROOT}/kube" \
    --defaults-file="$(echo "${ENV_FILES}" | tr ' ' ,)" \
    --use-memory-limits=false \
    --docker-registry "${IMAGE_REGISTRY}" \
    --docker-organization "${IMAGE_ORG}" \
    --repository "${IMAGE_PREFIX}"

# This is a small hack to make the output of make kube be compatible with K8s 1.6
perl -p -i -e 's@extensions/v1beta1@batch/v1@' kube/bosh-task/*.yml
