#!/usr/bin/env bash

set -o errexit -o nounset

GIT_ROOT="${GIT_ROOT:-$(git rev-parse --show-toplevel)}"

. "${GIT_ROOT}/make/include/versioning"

artifacts=("")
for variant in kube helm ; do
    tmp_dir=$(mktemp -d)
    trap "rm -rf '${tmp_dir}'" EXIT
    artifact="${ARTIFACT_NAME}-${variant}-${APP_VERSION}.zip"

    rm -f "${GIT_ROOT}/${artifact}"

    mkdir -p "${tmp_dir}"/{cf,uaa}

    cp -r "${GIT_ROOT}/${variant}/"* "${tmp_dir}/cf"
    cp -r "${GIT_ROOT}/src/uaa-fissile-release/${variant}/"* "${tmp_dir}/uaa"

    (
        cd "${tmp_dir}"
        zip -r9 "${GIT_ROOT}/${artifact}" ./*
    )

    rm -rf "${tmp_dir}"
    trap '' EXIT
    artifacts=("${artifact}" "${artifacts[@]}")
done

echo "Generated ${artifacts[*]}"
