#!/usr/bin/env bash

set -o errexit -o nounset

GIT_ROOT="${GIT_ROOT:-$(git rev-parse --show-toplevel)}"

. "${GIT_ROOT}/make/include/versioning"

if [[ ${FISSILE_STEMCELL} =~ ^.*fissile-stemcell-opensuse.*$ ]] ; then
    stemcell_os="opensuse"
elif [[ ${FISSILE_STEMCELL} =~ ^.*fissile-stemcell-sle.*$ ]] ; then
    stemcell_os="sle"
else
    echo "Unkown stemcell operating system: ${FISSILE_STEMCELL}"
    exit 1
fi

artifacts=("")

declare -A directories=(
    [cf]="${GIT_ROOT}/output"
    [uaa]="${GIT_ROOT}/src/uaa-fissile-release"
)

for project in "${!directories[@]}" ; do
    for variant in kube helm ; do
        artifact="output/${project}-${stemcell_os}-${variant}-${APP_VERSION}.tgz"
        (
            cd "${directories[${project}]}/${variant}"
            tar czf "${GIT_ROOT}/${artifact}" -- *
        )
        artifacts+=("${artifact}")
    done
done

echo "Generated ${artifacts[*]}"
