#!/usr/bin/env bash

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}
cd "${GIT_ROOT}"
source .envrc
source ${GIT_ROOT}/make/include/versioning

DOMAIN=${DOMAIN:-}

NETWORK_ENV=bin/settings/network.env
if test -n "${DOMAIN}"; then
    TMP=$(mktemp -d)
    cp "${NETWORK_ENV}" "${TMP}"
    trap "rm -rf ${TMP}" EXIT
    NETWORK_ENV="${TMP}/$(basename "${NETWORK_ENV}")"
    sed -e "s/^DOMAIN=.*/DOMAIN=${DOMAIN}/" \
        -e "s/^UAA_HOST=.*/UAA_HOST=uaa.${DOMAIN}/" \
        -e "s/^TCP_DOMAIN=.*/TCP_DOMAIN=tcp.${DOMAIN}/" \
        -i "${NETWORK_ENV}"
fi

BUILD_TARGET=kube

if [ "${1:-}" = "helm" ]; then
    BUILD_TARGET=helm
    USE_SECRETS_GENERATOR=--use-secrets-generator
fi

if [ "${BUILD_TARGET}" = "kube" ]; then
    # Overrides when generating kube config files instead of helm charts.
    FISSILE_OUTPUT_DIR="${PWD}/output/kube"
    FISSILE_DEFAULTS_FILE="bin/settings/settings.env,${NETWORK_ENV}"
    USE_SECRETS_GENERATOR=
fi

rm -rf "${FISSILE_OUTPUT_DIR}"

fissile build "${BUILD_TARGET}" "${USE_SECRETS_GENERATOR}"

if [ "${BUILD_TARGET}" = "helm" ]; then
    if [[ $FISSILE_STEMCELL =~ ^.*fissile-stemcell-opensuse.*$ ]] ; then
      chart_name_suffix="-opensuse"
    fi

    cat > "${FISSILE_OUTPUT_DIR}/Chart.yaml" << EOF
apiVersion: ${APP_VERSION}
description: A Helm chart for SUSE Cloud Foundry
name: cf${chart_name_suffix:-}
version: ${GIT_TAG}
EOF
    cp NOTES.txt  "${FISSILE_OUTPUT_DIR}/templates/"
elif [ "${BUILD_TARGET}" = "kube" ]; then
    # This is a small hack to make the output of make kube be compatible with K8s 1.6
    perl -p -i -e 's@extensions/v1beta1@batch/v1@' $(grep -rl 'kind: "Job"' "${FISSILE_OUTPUT_DIR}")
fi
