#!/usr/bin/env bash

set -o errexit -o nounset

GIT_ROOT="${GIT_ROOT:-$(git rev-parse --show-toplevel)}"

. "${GIT_ROOT}/make/include/versioning"

if [[ ! ${FISSILE_STEMCELL} =~ ^.*fissile-stemcell-sle.*$ ]] ; then
    echo "Unknown stemcell operating system: ${FISSILE_STEMCELL}"
    exit 1
fi

tmp_dir=$(mktemp -d)
trap "rm -rf '${tmp_dir}'" EXIT

artifacts=("")

declare -A directories=(
    [cf]="${GIT_ROOT}/output"
    [uaa]="${GIT_ROOT}/src/uaa-fissile-release"
)

for project in "${!directories[@]}" ; do
    for variant in kube helm ; do
        artifact="output/${project}-sle-${variant}-${APP_VERSION}.tgz"
        (
            if test -r "${directories[${project}]}/${variant}/Chart.yaml" ; then
                chart_name="$(awk '/^name:/ { print $2 }' "${directories[${project}]}/${variant}/Chart.yaml")"
                cp -r "${directories[${project}]}/${variant}" "${tmp_dir}/${chart_name}"
                cd "${tmp_dir}"
                tar czf "${GIT_ROOT}/${artifact}" -- "${chart_name}"
            else
                cd "${directories[${project}]}/${variant}"
                tar czf "${GIT_ROOT}/${artifact}" -- *
            fi
        )
        artifacts+=("${artifact}")
    done
done

echo "Generated ${artifacts[*]}"
