#!/usr/bin/env bash
set -o errexit -o nounset
GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)} 

SOURCE_OUTPUT_DIR=$GIT_ROOT/source-output
OSC_TARGET=OSCTEMP
OSC_BASE_PATH=Cloud:Platform:sources:scf
mkdir -p $GIT_ROOT/$OSC_TARGET
pushd $OSC_TARGET > /dev/null
rm -Rfv $OSC_BASE_PATH
osc checkout -M $OSC_BASE_PATH
pushd $OSC_BASE_PATH > /dev/null

# create or update new obs packages
PACKAGES=()
for FILE in `ls $SOURCE_OUTPUT_DIR/*.tar.gz`
do
	TMP=${FILE%.tar.gz}
	PACKAGE_NAME="scf_${TMP##*/}"
  if [ ! -d "$PACKAGE_NAME" ]; then
	  osc mkpac $PACKAGE_NAME
  fi
	pushd $PACKAGE_NAME
	cp $FILE .
  cp ${SOURCE_OUTPUT_DIR}/${TMP##*/}.spec .
	osc add *
	PACKAGES+=("$PACKAGE_NAME")
	# comment this in when adding all sources works
	popd > /dev/null
done
osc commit -m "Add sources"

# trigger legal_db scanning for all pacakges
for PACKAGE in ${PACKAGES[@]}
do
	curl -v -X POST http://legaldb.suse.de/packages -d api=https://api.opensuse.org/ -d project=$OSC_BASE_PATH -d package=$PACKAGE -d external_link=SCF -d priority=1
	echo $PACKAGE
done
popd > /dev/null
popd > /dev/null
