#!/bin/sh

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. ${GIT_ROOT}/make/include/versioning

ARTIFACT=${ARTIFACT_NAME}-kube-${APP_VERSION}.zip

rm ${GIT_ROOT}/${ARTIFACT} 2>/dev/null || true

cd kube && zip -r9 ${GIT_ROOT}/${ARTIFACT} * \
    ${NULL:-}

echo Generated ${ARTIFACT}
