#!/bin/sh

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. ${GIT_ROOT}/make/include/versioning

TARGET=${1}

case ${TARGET} in
    hcp)
        INSTANCE_DEFINITION_BASE=hcf-hcp-instance;;
    hcp-ha)
        INSTANCE_DEFINITION_BASE=hcf-hcp-instance-ha;;
    *)
        printf "\033[0;1;31mUnknown HCP package type ${TARGET}\033[0m\n" >&2
        exit 1;;
esac

ARTIFACT=${TARGET}-${APP_VERSION}.zip

zip -9 ${GIT_ROOT}/${ARTIFACT} \
    hcf-hcp.json hcf-hcp.3.json hcf-hcf.6.json \
    ${INSTANCE_DEFINITION_BASE}.json ${INSTANCE_DEFINITION_BASE}.3.json ${INSTANCE_DEFINITION_BASE}.6.json

echo Generated ${ARTIFACT}
