#!/bin/sh

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. ${GIT_ROOT}/make/include/versioning

ARTIFACT=hcp-${APP_VERSION}.zip

rm ${GIT_ROOT}/${ARTIFACT} 2>/dev/null || true

cd output && zip -9 ${GIT_ROOT}/${ARTIFACT} \
    sdl.json \
    instance-basic-dev.json \
    instance-ha-dev.json \
    ${NULL:-}

echo Generated ${ARTIFACT}
