#!/usr/bin/env bash

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}
DOCKER_FRIENDLY_TAGS=${DOCKER_FRIENDLY_TAGS:-'false'}

. ${GIT_ROOT}/make/include/versioning

case ${DOCKER_FRIENDLY_TAGS} in
    false)
        echo ${APP_VERSION}
        ;;
    *)
        echo ${DOCKER_APP_VERSION}
        ;;
esac
