#!/usr/bin/env bash

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

source "${GIT_ROOT}/make/include/defaults"

${GIT_ROOT}/make/run --set "enable.eirini=true" \
                     --set "env.EIRINI_PERSI_PLANS[0].id=default-storageclass" \
                     --set "env.EIRINI_PERSI_PLANS[0].description=Eirini persistence broker" \
                     --set "env.EIRINI_PERSI_PLANS[0].free=true" \
                     --set "env.EIRINI_PERSI_PLANS[0].kube_storage_class=${STORAGE_CLASS}" \
                     --set "env.EIRINI_PERSI_PLANS[0].default_size=1Gi" \
                     --set "env.EIRINI_PERSI_PLANS[0].name=default"