#!/bin/bash

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. ${GIT_ROOT}/make/include/versioning

cat <<-EOF
Branch             = ${GIT_BRANCH}
Tag                = ${GIT_TAG}
Prerel             = ${GIT_PREREL}
Commits            = ${GIT_COMMITS}
SHA                = ${GIT_SHA}
Describe           = ${GIT_DESCRIBE}
Artifact Name      = ${ARTIFACT_NAME}
App Version        = ${APP_VERSION}
Docker App Version = ${DOCKER_APP_VERSION}
EOF
