#!/bin/sh

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. ${GIT_ROOT}/make/include/versioning

echo "Branch           = '${GIT_BRANCH}'"
echo "Tag              = '${GIT_TAG}'"
echo "Commits          = '${GIT_COMMITS}'"
echo "SHA              = '${GIT_SHA}'"
echo "Describe         = '${GIT_DESCRIBE}'"
echo "Artifact Name    = '${ARTIFACT_NAME}'"
echo "Artifact Version = '${ARTIFACT_VERSION}'"
echo "App Version      = '${APP_VERSION}'"

