#!/bin/sh

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. "${GIT_ROOT}/.envrc"
. ${GIT_ROOT}/make/include/versioning

echo "docker registry = '${FISSILE_DOCKER_REGISTRY}'"
echo "docker org      = '${FISSILE_DOCKER_ORGANIZATION}'"
echo "scf version     = '${GIT_BRANCH}'"
echo "scf prefix      = '${FISSILE_REPOSITORY}'"
