#!/usr/bin/env bash

set -o errexit

: "${GIT_ROOT:=$(git rev-parse --show-toplevel)}"
source "${GIT_ROOT}/make/include/defaults"
source "${GIT_ROOT}/make/include/has_namespace"
source "${GIT_ROOT}/make/include/has_release"

stampy "${GIT_ROOT}/scf_metrics.csv" "$0" make-stop start
if has_release "${NAMESPACE}"; then
  helm delete --purge "${NAMESPACE}"
fi

if has_namespace "${NAMESPACE}"; then
  kubectl delete namespace "${NAMESPACE}"
fi
stampy "${GIT_ROOT}/scf_metrics.csv" "$0" make-stop 'done'
