#!/usr/bin/env bash

set -o errexit -o nounset

DIRECTORY_BLACKLIST="*-buildpack cflinuxfs2 opensuse42 busybox golang*"

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

HOMEDIR=~ 
BASEDIR="$HOMEDIR/.fissile/compilation"
OUTPUTDIR="$GIT_ROOT/source-output"

rm -rf $OUTPUTDIR
mkdir -p $OUTPUTDIR

pushd $BASEDIR
DIRS=`ls`
for DIR in $DIRS 
do
	DO_TAR=true
	SOURCE_PATH="$DIR/sources/var/vcap/source"
	SOURCE_NAME=`ls "$SOURCE_PATH"`
	SOURCE_SIZE=`du "$SOURCE_PATH"|tail -n1`
	for ITEM in $DIRECTORY_BLACKLIST
	do
		if [[ $SOURCE_NAME == $ITEM ]]; then
			DO_TAR=false
			echo "-----> $SOURCE_NAME IS BLACKLISTED (matches: $ITEM)"
		fi
	done
	if [[ $DO_TAR == true ]]; then
		echo "Creating tar archive for $SOURCE_NAME (source size: $SOURCE_SIZE)"
		tar czf "$OUTPUTDIR/${SOURCE_NAME}-${DIR}.tar.gz" "$SOURCE_PATH"
	fi
done

popd
