#!/bin/sh

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

DOCKER_RUNTIME=${DOCKER_RUNTIME:-'helioncf/terraform-tests'}

ENV_FILE=$(mktemp -q -u -t make.environ.XXXXXX)
trap "rm -rf ${ENV_FILE}" HUP INT TERM EXIT

cat /proc/self/environ > ${ENV_FILE}

PROVIDER="$1"
shift

EXTRA_MOUNTS=""

while test -n ${1-''} ; do
  EXTRA_MOUNTS="${EXTRA_MOUNTS} --volume ${1}:${1}:ro"
  shift
done

docker run \
       --rm \
       --volume ${GIT_ROOT}:${GIT_ROOT} \
       ${EXTRA_MOUNTS} \
       --volume ${ENV_FILE}:/environ:ro \
       ${DOCKER_RUNTIME} \
       ruby ${GIT_ROOT}/bin/run-terraform-tests.rb \
       --provider=${PROVIDER}
