#!/usr/bin/env bash

set -o errexit -o nounset

while ! ( kubectl get pods -n uaa | awk '{ if (match($2, /^([0-9]+)\/([0-9]+)$/, c) && c[1] != c[2] && !match($3, /Completed/)) { print ; exit 1 } }' )
do
  sleep 10
done
