#!/usr/bin/env bash

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. "${GIT_ROOT}/.envrc"
. "${GIT_ROOT}/src/uaa-fissile-release/.envrc"

make -C "${GIT_ROOT}/src/uaa-fissile-release" upgrade
