#!/bin/sh

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. "${GIT_ROOT}/make/include/registry"
. "${GIT_ROOT}/src/uaa-fissile-release/.envrc"

# IMAGE_REGISTRY and ORG have the same defaults, and pass through also.
# IMAGE_PREFIX we must not pass, on pain of getting images with the
# same name for different roles in SCF and UAA (mysql, uaa,
# role-packages).

unset IMAGE_PREFIX

make -C "${GIT_ROOT}/src/uaa-fissile-release" \
    kube-configs
