#!/usr/bin/env bash

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. "${GIT_ROOT}/.envrc"
. "${GIT_ROOT}/src/uaa-fissile-release/.envrc"
. "${GIT_ROOT}/make/include/versioning"

# FISSILE_DOCKER_REGISTRY and FISSILE_DOCKER_ORGANIZATION have the
# same defaults, and pass through also. FISSILE_REPOSITORY we must not
# pass, on pain of getting images with the same name for different
# roles in SCF and UAA (mysql, uaa, role-packages).

unset FISSILE_REPOSITORY

make -C "${GIT_ROOT}/src/uaa-fissile-release" images
