#!/usr/bin/env bash

# Upgrade a running CF using the current chart in output/helm. Assumes
# that only one revision is currently running. If more than one runs
# the last per helm's sorting order is chosen. (See **)

set -o errexit -o nounset

NAMESPACE="cf"
UAA_NAMESPACE="uaa"

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}
cd "${GIT_ROOT}"

. make/include/secrets

# Argument? (**)
# Setting the helm name to the namespace makes cleanup easier
RELEASE=${NAMESPACE}
echo Upgrading ${NAMESPACE} release \"${RELEASE}\" ...

stampy "${GIT_ROOT}/scf_metrics.csv" "$0" make-run start
stampy "${GIT_ROOT}/scf_metrics.csv" "$0" make-run::upgrade start

DOMAIN=${DOMAIN:-cf-dev.io}
TCP_DOMAIN=tcp.${DOMAIN}
UAA_HOST=uaa.${DOMAIN}
INSECURE_DOCKER_REGISTRIES="insecure-registry.${DOMAIN}:20005"

UAA_CA_CERT="$(get_secret "${UAA_NAMESPACE}" "uaa" "INTERNAL_CA_CERT")"

helm upgrade ${RELEASE} output/helm \
     --namespace ${NAMESPACE} \
     --values "bin/settings.yaml" \
     --set "env.DOMAIN=${DOMAIN}" \
     --set "env.TCP_DOMAIN=${TCP_DOMAIN}" \
     --set "env.UAA_HOST=${UAA_HOST}" \
     --set "env.INSECURE_DOCKER_REGISTRIES=${INSECURE_DOCKER_REGISTRIES}" \
     --set "kube.auth=rbac" \
     --set "kube.external_ips[0]=192.0.2.42" \
     --set "kube.external_ips[1]=$(dig +short "${DOMAIN}")" \
     --set "secrets.UAA_CA_CERT=${UAA_CA_CERT}" \
     "$@"

stampy "${GIT_ROOT}/scf_metrics.csv" "$0" make-run::upgrade end
stampy "${GIT_ROOT}/scf_metrics.csv" "$0" make-run 'done'
