#!/bin/bash

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. "${GIT_ROOT}/.envrc"
. ${GIT_ROOT}/make/include/versioning

${GIT_ROOT}/bin/validation.sh

# If you're looking at these quotes and wondering what I was thinking...
# The quotes need to be escaped so echo doesn't consume them, because they need
# to be used in the `docker run` command further on, which already has quotes
# inside quotes... shell really needs a %Q operator or something.

PROPMAP=$(mktemp -t vagrant-propmap.XXXXXX.yml)
OPTIONS=$(echo \
    --scf-prefix \"${FISSILE_REPOSITORY}\" \
    --scf-tag \"${DOCKER_APP_VERSION}\" \
    --scf-version \"${APP_VERSION}\" \
    --scf-root-dir \"${GIT_ROOT}\" \
    --provider vagrant \
    --property-map \"${PROPMAP}\" \
)

mkdir -p output

OUTFILE="vagrant.json"

fissile show properties --output yaml > ${PROPMAP}

DOCKER_RUNTIME=${DOCKER_RUNTIME:-'splatform/bosh-cli'}
ROLE_MANIFEST=${ROLE_MANIFEST:-'container-host-files/etc/hcf/config/role-manifest.yml'}

docker run \
       --rm \
       --volume ${GIT_ROOT}:${GIT_ROOT} \
       --volume ${PROPMAP}:${PROPMAP}:ro \
       --workdir ${GIT_ROOT} \
       --entrypoint bash \
       ${DOCKER_RUNTIME} -l -c "bin/vagrant-setup.rb ${OPTIONS} ${ROLE_MANIFEST}" \
    > ${OUTFILE}

rm -f ${PROPMAP}

printf "%bGenerated %s%b\n" "\033[0;32m" "${OUTFILE}" "\033[0m"
