- path: /releases/-
  type: replace
  value:
    name: cf-acceptance-tests
    url: {{ .Values.releases.defaults.url | quote }}
    version: 0.0.1
- path: /instance_groups/-
  type: replace
  value:
    azs:
    - z1
    instances: 1
    jobs:
    - name: acceptance-tests
      properties:
        acceptance_tests:
          admin_password: ((cf_admin_password))
          admin_user: admin
          api: https://api.((system_domain))
          apps_domain: ((system_domain))
          skip_ssl_validation: true
        bpm:
          enabled: true
      release: cf-acceptance-tests
    lifecycle: errand
    name: acceptance-tests
    networks:
    - name: default
    stemcell: default
    update:
      serial: true
    vm_type: minimal
