# Selectively remove jobs temporarily.
- type: remove
  path: /instance_groups/name=api/jobs/name=route_registrar
- type: remove
  path: /instance_groups/name=api/jobs/name=statsd_injector
- type: remove
  path: /instance_groups/name=api/jobs/name=file_server
- type: remove
  path: /instance_groups/name=api/jobs/name=policy-server
- type: remove
  path: /instance_groups/name=api/jobs/name=policy-server-internal
- type: remove
  path: /instance_groups/name=api/jobs/name=cc_uploader

# TODO: Remove this replace once all buildpacks are included.
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/install_buildpacks
  value:
  - name: binary_buildpack
    package: binary-buildpack-cflinuxfs3

# TODO: Remove these `remove` once all buildpack images are built.
- type: remove
  path: /instance_groups/name=api/jobs/name=dotnet-core-buildpack
- type: remove
  path: /instance_groups/name=api/jobs/name=go-buildpack
- type: remove
  path: /instance_groups/name=api/jobs/name=java-buildpack
- type: remove
  path: /instance_groups/name=api/jobs/name=nodejs-buildpack
- type: remove
  path: /instance_groups/name=api/jobs/name=nginx-buildpack
- type: remove
  path: /instance_groups/name=api/jobs/name=r-buildpack
- type: remove
  path: /instance_groups/name=api/jobs/name=php-buildpack
- type: remove
  path: /instance_groups/name=api/jobs/name=python-buildpack
- type: remove
  path: /instance_groups/name=api/jobs/name=ruby-buildpack
- type: remove
  path: /instance_groups/name=api/jobs/name=staticfile-buildpack

# core_file_pattern should be disabled as CC is not running on a VM.
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/core_file_pattern?
  value: false

# Override the blobstore URL.
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/buildpacks?/webdav_config?/private_endpoint?
  value: &blobstore_url https://((deployment-name))-singleton-blobstore:4443
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/droplets?/webdav_config?/private_endpoint?
  value: *blobstore_url
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/packages?/webdav_config?/private_endpoint?
  value: *blobstore_url
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/resource_pool?/webdav_config?/private_endpoint?
  value: *blobstore_url

# TODO: Figure out the DB encryption validation.
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/database_encryption?/skip_validation?
  value: true

# Override the addresses for the jobs under the api instance group.
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/ccdb/address?
  value: ((deployment-name))-database
- type: replace
  path: /instance_groups/name=api/jobs/name=routing-api/properties/routing_api/sqldb/host
  value: ((deployment-name))-database
- type: replace
  path: /instance_groups/name=api/jobs/name=routing-api/properties/routing_api/locket/api_location
  value: ((deployment-name))-diego-api:8891
- type: replace
  path: /instance_groups/name=api/jobs/name=routing-api/properties/dns_health_check_host?
  value: ((deployment-name))-uaa
- type: replace
  path: /instance_groups/name=api/jobs/name=routing-api/properties/uaa/token_endpoint?
  value: ((deployment-name))-uaa
# TODO: Figure out why it crashes the nginx job.
# - type: replace
#   path: /instance_groups/name=api/jobs/name=route_registrar/properties/nats?/machines
#   value:
#   - ((deployment-name))-nats

# Add empty BPM processes to buildpacks.
- type: replace
  path: /instance_groups/name=api/jobs/name=binary-buildpack/properties?/bosh_containerization?/bpm?/processes?
  value: []

# Add bosh_containerization properties for routing-api.
- type: replace
  path: /instance_groups/name=api/jobs/name=routing-api/properties/bosh_containerization?
  value:
    ports:
    - name: routing-api
      protocol: TCP
      internal: 3000
    run:
      memory: 128
      virtual-cpus: 4
