# Remove the PXC release and related variables.
- type: remove
  path: /releases/name=pxc
- type: remove
  path: /variables/name=pxc_galera_ca
- type: remove
  path: /variables/name=galera_server_certificate

# Set the common name for the mysql_server_certificate.
# An alternate name is not enough, the CC specifically looks at the common_name
- type: replace
  path: /variables/name=mysql_server_certificate/options/common_name?
  value: ((deployment-name))-database

# Add the cf-mysql-release.
- type: replace
  path: /releases/name=cf-mysql?
  value:
    name: cf-mysql
    url: docker.io/cfcontainerization
    version: 36.19.0
    sha1: ~

# Configure the persistent disk in the way that cf-operator can provision.
- type: remove
  path: /instance_groups/name=database/persistent_disk_type
- type: replace
  path: /instance_groups/name=database/persistent_disk?
  value: 20480 # 20GB

# Replace the jobs using the cf-mysql-release.
- type: replace
  path: /instance_groups/name=database/jobs
  value:
    - name: mysql
      release: cf-mysql
      properties:
        cf_mysql:
          mysql:
            enable_galera: false
            admin_password: "((cf_mysql_mysql_admin_password))"
            port: 3306
            binlog_enabled: false
            cluster_health:
              password: "((cf_mysql_mysql_cluster_health_password))"
            galera_healthcheck:
              db_password: "((cf_mysql_mysql_galera_healthcheck_password))"
              endpoint_username: galera_healthcheck
              endpoint_password: "((cf_mysql_mysql_galera_healthcheck_endpoint_password))"
            seeded_databases:
            - name: cloud_controller
              username: cloud_controller
              password: "((cc_database_password))"
            - name: credhub
              password: ((credhub_database_password))
              username: credhub
            - name: diego
              username: diego
              password: "((diego_database_password))"
            - name: network_connectivity
              username: network_connectivity
              password: "((network_connectivity_database_password))"
            - name: network_policy
              username: network_policy
              password: "((network_policy_database_password))"
            - name: routing-api
              username: routing-api
              password: "((routing_api_database_password))"
            - name: uaa
              username: uaa
              password: "((uaa_database_password))"
            - name: locket
              username: locket
              password: "((locket_database_password))"
            tls:
              ca_certificate: "((pxc_server_ca.certificate))"
              server_certificate: "((mysql_server_certificate.certificate))"
              server_key: "((mysql_server_certificate.private_key))"

# Add quarks properties. It adds the BPM configuration as cf-mysql-release lacks
# support for it upstream.
- type: replace
  path: /instance_groups/name=database/jobs/name=mysql/properties/quarks?
  value:
    ports:
    - name: mysql
      protocol: TCP
      internal: 3306
    run:
      healthcheck:
        mariadb_ctrl:
          readiness:
            exec:
              command:
              - /var/vcap/packages/mariadb/bin/mysqladmin
              - --defaults-file=/var/vcap/jobs/mysql/config/mylogin.cnf
              - ping
    bpm:
      processes:
      - name: mariadb_ctrl
        limits:
          open_files: 1048576
        persistent_disk: true
        executable: /bin/bash
        args:
          - -c
          - |
            wait_for_file() {
              local file_path="$1"
              local timeout="${2:-30}"
              until [[ -f "${file_path}" ]] || [[ "$timeout" == "0" ]]; do sleep 1; timeout=$(expr $timeout - 1); done
              if [[ "${timeout}" == 0 ]]; then return 1; fi
              return 0
            }

            /var/vcap/jobs/mysql/bin/mariadb_ctl start

            pid_file="/var/vcap/sys/run/mysql/mysql.pid"
            log_file="/var/vcap/sys/log/mysql/mariadb_ctrl.combined.log"

            wait_for_file "${pid_file}" || {
              echo "${pid_file} did not get created"
              exit 1
            }

            wait_for_file "${log_file}" || {
              echo "${log_file} did not get created"
              exit 1
            }

            tail \
              --pid $(cat "${pid_file}") \
              --follow "${log_file}"

{{- $root := . -}}
{{- range $path, $bytes := .Files.Glob "assets/operations/pre_render_scripts/database_*" }}
{{ $root.Files.Get $path }}
{{- end }}
