{{- if not .Values.features.eirini -}}

# Selectively remove jobs temporarily.
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=garden-cni
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=netmon
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=vxlan-policy-agent
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=silk-daemon
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=silk-cni

# Enable BPM on garden.
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/bpm?/enabled
  value: true

# Override the addresses for the jobs under the diego-cell instance group.
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=route_emitter/properties/uaa/hostname?
  value: ((deployment-name))-uaa
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=route_emitter/properties/diego/route_emitter/nats?/machines
  value:
  - ((deployment-name))-nats
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=route_emitter/properties/diego/route_emitter/bbs/api_location?
  value: ((deployment-name))-diego-api:8889
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=route_emitter/properties/locks?/locket/hostname
  value: ((deployment-name))-diego-api
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=route_emitter/properties/routing_api?/url
  value: http://((deployment-name))-api
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=cfdot/properties/bbs?/hostname
  value: ((deployment-name))-diego-api
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=cfdot/properties/locket?/hostname
  value: ((deployment-name))-diego-api
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/set_kernel_parameters?
  value: false

# Temporarily remove garden network_plugin.
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/network_plugin
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/network_plugin_extra_args

# Add quarks properties for garden.
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/quarks?
  value:
    run:
      healthcheck:
        garden:
          readiness: &garden_readiness
            exec:
              command: [sh, -c, 'ss -nlt | grep "LISTEN.*:17019"']
    post_start:
      condition: *garden_readiness

# Add quarks properties for route_emitter.
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=route_emitter/properties/quarks?
  value:
    run:
      healthcheck:
        route_emitter:
          readiness: &route_emitter_readiness
            exec:
              command: [curl, --fail, --silent, http://127.0.0.1:17011/ping]
    post_start:
      condition: *route_emitter_readiness

# Add quarks properties for rep.
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/quarks?
  value:
    ports:
    - name: rep
      protocol: TCP
      internal: 1800
    - name: rep-tls
      protocol: TCP
      internal: 1801
    run:
      security_context:
        privileged: true
      healthcheck:
        rep:
          readiness: &rep_readiness
            exec:
              command: [sh, -c, 'ss -nlt | grep "LISTEN.*:1800"']
    post_start:
      condition: *rep_readiness

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=cflinuxfs3-rootfs-setup/properties/quarks?/bpm/processes
  value: []
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=cfdot/properties/quarks?/bpm/processes
  value: []

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/diego/rep/locket?/api_location
  value: ((deployment-name))-diego-api:8891

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/diego/rep/bbs?/api_location
  value: ((deployment-name))-diego-api:8889

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/diego/rep/advertise_domain?
  value: ((deployment-name))-diego-cell

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/diego/rep/preloaded_rootfses
  value:
  - cflinuxfs3:/var/vcap/data/rep/cflinuxfs3/rootfs.tar

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/network_pool?
  value: 10.38.0.0/16

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/apparmor_profile?
  value: ""

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/containerd_mode
  value: false

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/cleanup_process_dirs_on_wait
  value: false

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties?/garden?/disable_swap_limit?
  value: true

{{- $root := . -}}
{{- range $path, $bytes := .Files.Glob "assets/operations/pre_render_scripts/diego-cell_*" }}
{{ $root.Files.Get $path }}
{{- end }}

{{- end }}
