# Enable BPM on garden.
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/bpm?
  value:
    enabled: true

# Add bosh_containerization properties.
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/bosh_containerization?
  value:
    run:
      memory: 4096
      virtual-cpus: 2
      healthcheck:
        garden:
          readiness: &probe
            exec:
              command: ['sh', '-c', 'ss -nlt | grep "LISTEN.*:17019"']
          liveness: *probe


# Temporarily remove garden network_plugin.
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/network_plugin
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/network_plugin_extra_args

# Selectively remove jobs temporarily.
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=cflinuxfs3-rootfs-setup
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=rep
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=cfdot
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=route_emitter
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=garden-cni
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=netmon
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=vxlan-policy-agent
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=silk-daemon
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=silk-cni
