{{- if not .Values.features.eirini -}}

# Selectively remove jobs temporarily.
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=garden-cni
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=netmon
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=vxlan-policy-agent
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=silk-daemon
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=silk-cni

# Enable BPM on garden.
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/bpm?/enabled
  value: true

# Override the addresses for the jobs under the diego-cell instance group.
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=route_emitter/properties/uaa/hostname?
  value: {{ .Values.deployment_name }}-uaa
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=route_emitter/properties/diego/route_emitter/nats?/machines
  value:
  - {{ .Values.deployment_name }}-nats
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=route_emitter/properties/diego/route_emitter/bbs/api_location?
  value: {{ .Values.deployment_name }}-diego-api:8889
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=route_emitter/properties/locks?/locket/hostname
  value: {{ .Values.deployment_name }}-diego-api
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=route_emitter/properties/routing_api?/url
  value: http://{{ .Values.deployment_name }}-api
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=cfdot/properties/bbs?/hostname
  value: {{ .Values.deployment_name }}-diego-api
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=cfdot/properties/locket?/hostname
  value: {{ .Values.deployment_name }}-diego-api
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/set_kernel_parameters?
  value: false

# Temporarily remove garden network_plugin.
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/network_plugin
- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/network_plugin_extra_args

# Add quarks properties for garden.
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/quarks?
  value:
    run:
      healthcheck:
        garden:
          readiness:
            exec:
              command: [curl, --head, --fail, --silent, http://127.0.0.1:17019/debug/vars]
          liveness:
            exec:
              command: [pidof, gdn]
    post_start:
      condition:
        exec:
          command: [sh, -c, 'ss -nlt sport = 17019 | grep "LISTEN.*:17019"']

# Add quarks properties for route_emitter.
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=route_emitter/properties/quarks?
  value:
    run:
      healthcheck:
        route_emitter:
          readiness: &route_emitter_readiness
            exec:
              command: [curl, --fail, --silent, http://127.0.0.1:17011/ping]
          liveness:
            exec:
              command: [pidof, route-emitter]
    post_start:
      condition: *route_emitter_readiness

# Add quarks properties for rep.
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/quarks?
  value:
    ports:
    - name: rep-tls
      protocol: TCP
      internal: 1801
    run:
      security_context:
        capabilities:
          add:
          - SYS_ADMIN
      healthcheck:
        rep:
          readiness:
            exec:
              command:
              - curl
              - --head
              - --fail
              - --insecure
              - --cert
              - /var/vcap/jobs/rep/config/certs/tls.crt
              - --key
              - /var/vcap/jobs/rep/config/certs/tls.key
              - https://127.0.0.1:1800/ping
          liveness:
            exec:
              command: [pidof, rep]
    post_start:
      condition:
        exec:
          command: [sh, -c, 'ss -nlt sport = 1800 | grep "LISTEN.*:1800"']

# Set the unconfined AppArmor profile for bpm-pre-start-rep in order to perform mounts.
# This works in combination with CAP_SYS_ADMIN Linux capability.
- type: replace
  path: /instance_groups/name=diego-cell/env?/bosh/agent/settings/annotations/container.apparmor.security.beta.kubernetes.io~1bpm-pre-start-rep
  value: unconfined

# Set the unconfined AppArmor profile for rep-rep in order to perform mounts.
# This works in combination with CAP_SYS_ADMIN Linux capability.
- type: replace
  path: /instance_groups/name=diego-cell/env?/bosh/agent/settings/annotations/container.apparmor.security.beta.kubernetes.io~1rep-rep
  value: unconfined

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=cflinuxfs3-rootfs-setup/properties/quarks?/bpm/processes
  value: []
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=cfdot/properties/quarks?/bpm/processes
  value: []

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/diego/rep/locket?/api_location
  value: {{ .Values.deployment_name }}-diego-api:8891

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/diego/rep/bbs?/api_location
  value: {{ .Values.deployment_name }}-diego-api:8889

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/diego/rep/advertise_domain?
  value: {{ .Values.deployment_name }}-diego-cell

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/diego/rep/preloaded_rootfses
  value:
  - cflinuxfs3:/var/vcap/data/rep/cflinuxfs3/rootfs.tar

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/network_pool?
  value: 10.38.0.0/16

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/apparmor_profile?
  value: ""

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/containerd_mode
  value: false

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/cleanup_process_dirs_on_wait
  value: false

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties?/garden?/disable_swap_limit?
  value: true

{{- $root := . -}}
{{- range $path, $bytes := .Files.Glob "assets/operations/pre_render_scripts/diego-cell_*" }}
{{ $root.Files.Get $path }}
{{- end }}

{{- end }}
