# Selectively remove jobs temporarily.
- type: remove
  path: /instance_groups/name=diego-api/jobs/name=silk-controller

# Override the addresses for the jobs under the diego-api instance group.
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=locket/properties/diego/locket/sql/db_host
  value: {{ .Values.deployment_name }}-database
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/sql/db_host
  value: {{ .Values.deployment_name }}-database
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/locket?/api_location
  value: 127.0.0.1:8891
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/auctioneer?/api_location
  value: {{ .Values.deployment_name }}-scheduler:9016
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/advertisement_base_hostname?
  value: {{ .Values.deployment_name }}-diego-api
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/health_addr?
  value: 0.0.0.0:8890
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=cfdot/properties/bbs?/hostname
  value: 127.0.0.1
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=cfdot/properties/locket?/hostname
  value: 127.0.0.1

# Disable tuning /proc/sys kernel parameters as locket and bbs are running on containers.
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=locket/properties/set_kernel_parameters?
  value: false
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/set_kernel_parameters?
  value: false

# Add quarks properties for locket.
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=locket/properties/quarks?
  value:
    ports:
    - name: locket
      protocol: TCP
      internal: 8891
    run:
      healthcheck:
        locket:
          readiness:
            exec:
              command:
              - /var/vcap/packages/cfdot/bin/cfdot
              - locks
              - --locketAPILocation=localhost:8891
              # We need to both give --skipCertVerify and provide a CA cert;
              # skipping the former ends up with context deadline exceeded, and
              # skipping the latter errors out failing to read file ""
              - --skipCertVerify
              - --caCertFile=/var/vcap/jobs/locket/config/certs/ca.crt
              - --clientCertFile=/var/vcap/jobs/locket/config/certs/server.crt
              - --clientKeyFile=/var/vcap/jobs/locket/config/certs/server.key

# Add quarks properties for bbs.
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/quarks?
  value:
    ports:
    - name: cell-bbs-api
      protocol: TCP
      internal: 8889
    run:
      healthcheck:
        bbs:
          readiness:
            httpGet:
              port: 8890
    post_start:
      condition:
        exec:
          command:
          - sh
          - -c
          - ss -nlt sport = 8889 | grep "LISTEN.*:8889"

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=cfdot/properties/quarks?/bpm/processes
  value: []

{{- $root := . -}}
{{- range $path, $bytes := .Files.Glob "assets/operations/pre_render_scripts/diego-api_*" }}
{{ $root.Files.Get $path }}
{{- end }}
