# Add quarks properties for loggregator_trafficcontroller.
- type: replace
  path: /instance_groups/name=log-api/jobs/name=loggregator_trafficcontroller/properties/quarks?
  value:
    envs:
    - name: TRAFFIC_CONTROLLER_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    ports:
    - name: dropsonde
      protocol: TCP
      internal: 8081
    run:
      healthcheck:
        loggregator_trafficcontroller:
          readiness:
            exec:
              command: [curl, --fail, --silent, --head, http://localhost:14825/health]

# Add quarks properties for reverse_log_proxy.
- type: replace
  path: /instance_groups/name=log-api/jobs/name=reverse_log_proxy/properties/reverse_log_proxy?/health_addr
  value: "localhost:14826"
- type: replace
  path: /instance_groups/name=log-api/jobs/name=reverse_log_proxy/properties/quarks?
  value:
    ports:
    - name: grpc-egress
      protocol: TCP
      internal: 8082
    run:
      healthcheck:
        reverse_log_proxy:
          readiness:
            exec:
              command: [curl, --fail, --silent, --head, http://localhost:14826/health]

- type: replace
  path: /instance_groups/name=log-api/jobs/name=reverse_log_proxy_gateway/properties/quarks?/bpm/processes/name=reverse_log_proxy_gateway/env/PPROF_PORT?
  value: "33045"
- type: replace
  path: /instance_groups/name=log-api/jobs/name=reverse_log_proxy_gateway/properties/quarks?/run/healthcheck/reverse_log_proxy_gateway/readiness/exec/command
  value: [curl, --fail, --head, --silent, http://localhost:33045/debug/pprof/cmdline]

- type: replace
  path: /instance_groups/name=log-api/jobs/name=route_registrar/properties/quarks?/run/healthcheck/route_registrar
  value:
    readiness: ~
      # The route registrar doesn't expose anything to indicate if the
      # routes are healthy
