# Add quarks properties for the gorouter job.
- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/quarks?
  value:
    ports:
    - name: router
      protocol: TCP
      internal: 8000
      public: true
    - name: router-ssl
      protocol: TCP
      internal: 443
    run:
      healthcheck:
        gorouter:
          readiness:
            httpGet:
              port: 8080
              path: /health
    post_start:
      condition:
        exec:
          command: [curl, --fail, --head, http://127.0.0.1:8080/health]

- type: replace
  path: /instance_groups/name=router/jobs/name=loggr-udp-forwarder/properties/quarks?/run/healthcheck/loggr-udp-forwarder
  value:
    readiness:
      exec:
        command: [sh, -c, 'ss -nlu sport = 3457 | grep :3457']

# Add necessary labels to the router instance group so that the service can select it to create the
# endpoint.
- type: replace
  path: /instance_groups/name=router/env?/bosh/agent/settings/labels/app.kubernetes.io~1component
  value: "router"
- type: replace
  path: /instance_groups/name=router/env?/bosh/agent/settings/labels/app.kubernetes.io~1instance
  value: {{ .Release.Name | quote }}
- type: replace
  path: /instance_groups/name=router/env?/bosh/agent/settings/labels/app.kubernetes.io~1version
  value: {{ default .Chart.Version .Chart.AppVersion | quote }}
