# Override the addresses for the jobs under the router instance group.
- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/router/dns_health_check_host?
  value: {{ .Values.deployment_name }}-uaa
- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/uaa/token_endpoint?
  value: {{ .Values.deployment_name }}-uaa
- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/routing_api/uri?
  value: http://{{ .Values.deployment_name }}-api
- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/nats?/machines
  value:
  - {{ .Values.deployment_name }}-nats

# Add quarks properties for the gorouter job.
- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/quarks?
  value:
    ports:
    - name: router
      protocol: TCP
      internal: 8000
      public: true
    - name: router-ssl
      protocol: TCP
      internal: 443
    run:
      healthcheck:
        gorouter:
          readiness: &gorouter_readiness
            exec:
              command: ['curl', '--fail', '--head', 'http://127.0.0.1:8080/health']
    post_start:
      condition: *gorouter_readiness

# Add necessary labels to the router instance group so that the service can select it to create the
# endpoint.
- type: replace
  path: /instance_groups/name=router/env?/bosh/agent/settings/labels/app.kubernetes.io~1component
  value: "router"
- type: replace
  path: /instance_groups/name=router/env?/bosh/agent/settings/labels/app.kubernetes.io~1instance
  value: {{ .Release.Name | quote }}
- type: replace
  path: /instance_groups/name=router/env?/bosh/agent/settings/labels/app.kubernetes.io~1version
  value: {{ default .Chart.Version .Chart.AppVersion | quote }}
