# Override the addresses for the jobs under the router instance group.
- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/router/dns_health_check_host?
  value: ((deployment-name))-uaa
- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/uaa/token_endpoint?
  value: ((deployment-name))-uaa
- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/routing_api/uri?
  value: http://((deployment-name))-api
- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/nats?/machines
  value:
  - ((deployment-name))-nats
