# Override the addresses for the jobs under the scheduler instance group.
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/ccdb/address?
  value: sql-db.service.cf.internal
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/ccdb/address
  value: sql-db.service.cf.internal

# Add quarks properties for the scheduler job.
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=scheduler/properties/quarks?/run/healthcheck/scheduler
  value:
    readiness:
      exec:
        command: [curl, --fail, --head, --silent, http://127.0.0.1:8080/health]

# Add quarks properties for the auctioneer job.
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=auctioneer/properties/quarks?
  value:
    ports:
    - name: auctioneer
      protocol: TCP
      internal: 9016
    run:
      healthcheck:
        auctioneer:
          readiness:
            # There is no health check, just depend on the port being open
            tcpSocket:
              port: 9016

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/quarks?/run/healthcheck/cloud_controller_clock
  value:
    readiness:
      # There is no good readiness check for the scheduled tasks
      exec:
        command: [pgrep, --full, clock:start]

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/quarks?/run/healthcheck/cc_deployment_updater
  value:
    readiness:
      exec:
        command:
        # We should sleep about once every 5 seconds; check that the last entry was no more than 2 cycles ago
        - sh
        - -c
        - tac /var/vcap/sys/log/cc_deployment_updater/cc_deployment_updater.log | grep --max-count=1 Sleeping | jq -r '(now - .timestamp) < 10'
    liveness:
      exec:
        command: [pgrep, --full, deployment_updater:start]

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=statsd_injector/properties/quarks?/run/healthcheck/statsd_injector/readiness/exec/command
  value: [/bin/sh, -c, ss -nlu src localhost:8125 | grep :8125]

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=tps/properties/quarks?/run/healthcheck/watcher/readiness/exec/command
  value: [curl, --fail, --silent, http://127.0.0.1:17015/debug/pprof/cmdline]

# Add quarks properties for the ssh_proxy job.
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=ssh_proxy/properties/diego/ssh_proxy/disable_healthcheck_server
  value: false
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=ssh_proxy/properties/quarks?
  value:
    ports:
    - name: ssh-proxy
      protocol: TCP
      internal: 2222
    run:
      healthcheck:
        ssh_proxy:
          readiness:
            httpGet:
              port: 2223

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=log-cache-scheduler/properties?/quarks/run/healthcheck/log-cache-scheduler/readiness/exec/command
  value: [curl, --fail, --silent, http://localhost:6064/debug/pprof/cmdline]

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cfdot/properties/quarks?/bpm/processes
  value: []

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=log-cache-expvar-forwarder/properties/quarks?/envs?
  value:
  - name: INSTANCE_ADDR
    value: {{ .Values.deployment_name }}-scheduler:8080
  - name: INSTANCE_ID
    value: "0"

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=log-cache-expvar-forwarder/properties/quarks?/run/healthcheck/log-cache-expvar-forwarder
  value:
    readiness: ~
      # We do not have a good thing to use as a readiness probe

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=log-cache-expvar-forwarder/provides?
  value:
    log-cache-expvar-forwarder: {as: this_is_not_used}
