
# Override the addresses for the jobs under the scheduler instance group.
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/ccdb/address?
  value: {{ .Values.deployment_name }}-database
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/cc/diego?/bbs/url
  value: https://{{ .Values.deployment_name }}-diego-api:8889
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/cc/diego?/cc_uploader_url
  value: http://{{ .Values.deployment_name }}-api:9090
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/cc/diego?/file_server_url
  value: http://{{ .Values.deployment_name }}-api:8080
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/cc/locket?/host
  value: {{ .Values.deployment_name }}-diego-api
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=auctioneer/properties/diego/auctioneer/bbs?/api_location
  value: {{ .Values.deployment_name }}-diego-api:8889
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=auctioneer/properties/diego/auctioneer/locket?/api_location
  value: {{ .Values.deployment_name }}-diego-api:8891
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=tps/properties/capi/tps/bbs?/api_location
  value: {{ .Values.deployment_name }}-diego-api:8889
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=tps/properties/capi/tps/cc/internal_service_hostname?
  value: {{ .Values.deployment_name }}-api
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=tps/properties/capi/tps/watcher/locket/api_location
  value: {{ .Values.deployment_name }}-diego-api:8891
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/ccdb/address
  value: {{ .Values.deployment_name }}-database
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/buildpacks?/webdav_config/private_endpoint
  value: &blobstore_url https://{{ .Values.deployment_name }}-singleton-blobstore:4443
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/droplets?/webdav_config/private_endpoint
  value: *blobstore_url
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/packages?/webdav_config/private_endpoint
  value: *blobstore_url
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/resource_pool?/webdav_config/private_endpoint
  value: *blobstore_url
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/diego?/bbs/url
  value: https://{{ .Values.deployment_name }}-diego-api:8889
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/diego?/cc_uploader_url
  value: http://{{ .Values.deployment_name }}-api:9090
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/diego?/file_server_url
  value: http://{{ .Values.deployment_name }}-api:8080
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/internal_service_hostname?
  value: {{ .Values.deployment_name }}-api
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/uaa?/internal_url
  value: {{ .Values.deployment_name }}-uaa
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/credhub_api?/hostname
  value: {{ .Values.deployment_name }}-credhub
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cfdot/properties/bbs?/hostname
  value: {{ .Values.deployment_name }}-diego-api
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cfdot/properties/locket?/hostname
  value: {{ .Values.deployment_name }}-diego-api
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=scheduler/properties/scalablesyslog/scheduler/api/url
  value: https://{{ .Values.deployment_name }}-api:9023
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=scheduler/properties/scalablesyslog/scheduler/tls/api/cn
  value: {{ .Values.deployment_name }}-api
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=ssh_proxy/properties/diego/ssh_proxy/bbs?/api_location
  value: {{ .Values.deployment_name }}-diego-api:8889
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=ssh_proxy/properties/diego/ssh_proxy/uaa?/url
  value: https://{{ .Values.deployment_name }}-uaa

# Add quarks properties for the scheduler job.
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=scheduler/properties/quarks?/run/healthcheck/scheduler
  value:
    readiness:
      exec:
        command: [curl, --fail, --head, --silent, http://127.0.0.1:8080/health]

# Add quarks properties for the auctioneer job.
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=auctioneer/properties/quarks?
  value:
    ports:
    - name: auctioneer
      protocol: TCP
      internal: 9016
    run:
      healthcheck:
        auctioneer:
          readiness:
            # There is no health check, just depend on the port being open
            tcpSocket:
              port: 9016

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/quarks?/run/healthcheck/cloud_controller_clock
  value:
    readiness:
      # There is no good readiness check for the scheduled tasks
      exec:
        command: [pgrep, --full, clock:start]

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/quarks?/run/healthcheck/cc_deployment_updater
  value:
    readiness:
      exec:
        command:
        # We should sleep about once every 5 seconds; check that the last entry was no more than 2 cycles ago
        - sh
        - -c
        - tac /var/vcap/sys/log/cc_deployment_updater/cc_deployment_updater.log | grep --max-count=1 Sleeping | jq -r '(now - .timestamp) < 10'
    liveness:
      exec:
        command: [pgrep, --full, deployment_updater:start]

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=statsd_injector/properties/quarks?/run/healthcheck/statsd_injector/readiness/exec/command
  value: [/bin/sh, -c, ss -nlu src localhost:8125 | grep :8125]

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=tps/properties/quarks?/run/healthcheck/watcher/readiness/exec/command
  value: [curl, --fail, --silent, http://127.0.0.1:17015/debug/pprof/cmdline]

# Add quarks properties for the ssh_proxy job.
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=ssh_proxy/properties/diego/ssh_proxy/disable_healthcheck_server
  value: false
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=ssh_proxy/properties/quarks?
  value:
    ports:
    - name: ssh-proxy
      protocol: TCP
      internal: 2222
    run:
      healthcheck:
        ssh_proxy:
          readiness:
            httpGet:
              port: 2223

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=log-cache-scheduler/properties?/quarks/run/healthcheck/log-cache-scheduler/readiness/exec/command
  value: [curl, --fail, --silent, http://localhost:6064/debug/pprof/cmdline]

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cfdot/properties/quarks?/bpm/processes
  value: []

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=log-cache-expvar-forwarder/properties/quarks?/envs?
  value:
  - name: INSTANCE_ADDR
    value: {{ .Values.deployment_name }}-scheduler:8080
  - name: INSTANCE_ID
    value: "0"

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=log-cache-expvar-forwarder/properties/quarks?/run/healthcheck/log-cache-expvar-forwarder
  value:
    readiness: ~
      # We do not have a good thing to use as a readiness probe

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=log-cache-expvar-forwarder/provides?
  value:
    log-cache-expvar-forwarder: {as: this_is_not_used}

