# Configure the persistent disk in the way that cf-operator can provision.
- type: remove
  path: /instance_groups/name=singleton-blobstore/persistent_disk_type
- type: replace
  path: /instance_groups/name=singleton-blobstore/persistent_disk?
  value: 102400 # 100GB

- type: replace
  path: /instance_groups/name=singleton-blobstore/jobs/name=blobstore/properties/quarks?
  value:
    ports:
    - name: http
      protocol: TCP
      internal: 8080
    - name: https
      protocol: TCP
      internal: 4443
    run:
      security_context:
        runAsUser: 1000 # vcap
      healthcheck:
        nginx:
          readiness:
            tcpSocket:
              port: 8080
          liveness:
            exec:
              command: [pgrep, --full, 'nginx: master process']
        url_signer:
          readiness:
            exec:
              command: [test, -S, /var/vcap/data/blobstore/signer.sock]

- type: replace
  path: /instance_groups/name=singleton-blobstore/jobs/name=route_registrar/properties/quarks?/run/healthcheck/route_registrar
  value:
    readiness: ~
      # The route registrar doesn't expose anything to indicate if the
      # routes are healthy.

{{- $root := . -}}
{{- range $path, $bytes := .Files.Glob "assets/operations/pre_render_scripts/singleton-blobstore_*" }}
{{ $root.Files.Get $path }}
{{- end }}
