# Configure the persistent disk in the way that cf-operator can provision.
- type: remove
  path: /instance_groups/name=singleton-blobstore/persistent_disk_type
- type: replace
  path: /instance_groups/name=singleton-blobstore/persistent_disk?
  value: 102400 # 100GB

# Override the addresses for the jobs under the singleton-blobstore instance group.
- type: replace
  path: /instance_groups/name=singleton-blobstore/jobs/name=blobstore/properties/internal_server_name?
  value: {{ .Values.deployment_name }}-singleton-blobstore
- type: replace
  path: /instance_groups/name=singleton-blobstore/jobs/name=route_registrar/properties/nats?/machines
  value:
  - {{ .Values.deployment_name }}-nats
- type: replace
  path: /instance_groups/name=singleton-blobstore/jobs/name=route_registrar/properties/route_registrar?/routing_api/api_url
  value: http://{{ .Values.deployment_name }}-api:3000
- type: replace
  path: /instance_groups/name=singleton-blobstore/jobs/name=route_registrar/properties/route_registrar?/routing_api/oauth_url
  value: https://{{ .Values.deployment_name }}-uaa:8443

- type: replace
  path: /instance_groups/name=singleton-blobstore/jobs/name=blobstore/properties/quarks?
  value:
    ports:
    - name: http
      protocol: TCP
      internal: 8080
    - name: https
      protocol: TCP
      internal: 4443
    run:
      security_context:
        runAsUser: 1000 # vcap
      healthcheck:
        nginx:
          readiness:
            tcpSocket:
              port: 8080
          liveness:
            exec:
              command: [pgrep, --full, 'nginx: master process']
        url_signer:
          readiness:
            exec:
              command: [test, -S, /var/vcap/data/blobstore/signer.sock]

- type: replace
  path: /instance_groups/name=singleton-blobstore/jobs/name=route_registrar/properties/quarks?/run/healthcheck/route_registrar
  value:
    readiness: ~
      # The route registrar doesn't expose anything to indicate if the
      # routes are healthy.

{{- $root := . -}}
{{- range $path, $bytes := .Files.Glob "assets/operations/pre_render_scripts/singleton-blobstore_*" }}
{{ $root.Files.Get $path }}
{{- end }}
