# Selectively remove jobs temporarily.
- type: remove
  path: /instance_groups/name=uaa/jobs/name=route_registrar
- type: remove
  path: /instance_groups/name=uaa/jobs/name=statsd_injector

# Override the database address.
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaadb/address?
  value: ((deployment-name))-database

# Add the ((deployment-name))-uaa alternative name for the uaa_ssl.
- type: replace
  path: /variables/name=uaa_ssl/options/alternative_names/-
  value: ((deployment-name))-uaa

# Fix uaa.zones.internal.hostnames to point to the correct service DNS.
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/zones/internal/hostnames
  value:
  - ((deployment-name))-uaa

# TODO: Figure out why it crashes the uaa job.
# # Fix the nats address for the route_registrar.
# - type: replace
#   path: /instance_groups/name=uaa/jobs/name=route_registrar/properties/nats?/machines
#   value:
#   - ((deployment-name))-nats

# Add bosh_containerization properties.
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/bosh_containerization?
  value:
    ports:
    - name: http
      protocol: TCP
      internal: 8080
    - name: https
      protocol: TCP
      internal: 8443
    run:
      memory: 1532
      virtual-cpus: 2
      healthcheck:
        uaa:
          readiness: &probe
            handler:
              exec:
                command: ['sh', '-c', '/var/vcap/jobs/uaa/bin/health_check']
          liveness: *probe
