{{- define "scf.implicit-var" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment_name }}.var-{{ index . "variable-name" | replace "_" "-" }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "scf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "scf.chart" . }}
type: Opaque
stringData:
  value: {{ index .Values ( index . "variable-name" ) | quote }}
{{- end }}

{{ include "scf.implicit-var" (merge (dict "variable-name" "system_domain") .) }}
{{ include "scf.implicit-var" (merge (dict "variable-name" "deployment_name") .) }}
{{ include "scf.implicit-var" (merge (dict "variable-name" "container_image_prefix") .) }}
