#!/usr/bin/env bash

set -o errexit -o nounset

: "${GIT_ROOT:=$(git rev-parse --show-toplevel)}"
source "${GIT_ROOT}/.envrc"
source "${GIT_ROOT}/bin/common/versions.sh"

: "${STRATOS_HELM_NAME:=stratos}"
: "${STRATOS_NAMESPACE:=stratos}"
: "${VAGRANT_EXTERNAL_IP:=$(ip -4 addr show eth1 | grep --only-matching --perl-regexp "(?<=inet )[\\d\\.]+(?=/)")}"
