#!/usr/bin/env bash

set -o errexit -o nounset

: "${GIT_ROOT:=$(git rev-parse --show-toplevel)}"
source "${GIT_ROOT}/bin/common/versions.sh"
source "${GIT_ROOT}/make/include/defaults"
source "${GIT_ROOT}/make/include/has_release"

if ! has_release "${STRATOS_HELM_RELEASE}"; then
  subcommand="install"

  args=(
    "${STRATOS_CHART}"
    --name "${STRATOS_HELM_RELEASE}"
    --namespace "${STRATOS_NAMESPACE}"
  )
else
  subcommand="upgrade"

  args=(
    "${STRATOS_HELM_RELEASE}"
    "${STRATOS_CHART}"
  )
fi

values=(
  --set "uaa.host=${CF_NAMESPACE}.${UAA_HOST}"
  --set "uaa.port=${UAA_PORT}"
  --set "uaa.consoleClient=${UAA_CLIENT_ID}"
  --set "uaa.consoleClientSecret=${UAA_CLIENT_SECRET}"
  --set "uaa.consoleAdminIdentifier=${UAA_ADMIN_IDENTIFIER}"
  --set "uaa.skipSSLValidation=${UAA_SKIP_SSL_VALIDATION}"
  --set "kube.storage_class.persistent=${STORAGE_CLASS}"
  --set "kube.external_ip=${VAGRANT_EXTERNAL_IP}"
)

helm "${subcommand}" "${args[@]}" "${values[@]}"
