#!/usr/bin/env bash

set -o errexit

source "${BASH_SOURCE%/*}/_env"
source "${GIT_ROOT}/make/include/has_release"

if [ "$(has_release "${STRATOS_NAMESPACE}")" -eq 0 ]; then
  helm delete --purge "${STRATOS_NAMESPACE}"
  kubectl delete namespace "${STRATOS_NAMESPACE}"
fi
