#!/usr/bin/env bash

set -o errexit -o nounset

: "${GIT_ROOT:=$(git rev-parse --show-toplevel)}"
source "${GIT_ROOT}/make/include/defaults"
source "${GIT_ROOT}/make/include/has_namespace"
source "${GIT_ROOT}/make/include/has_release"

if has_release "${STRATOS_HELM_RELEASE}"; then
  helm delete --purge "${STRATOS_HELM_RELEASE}"
fi

if has_namespace "${STRATOS_NAMESPACE}"; then
  kubectl delete namespace "${STRATOS_NAMESPACE}"
fi
